baseURL: https://www.danielreddjones.com
languageCode: "en-us"
title: "Daniel Jones CV"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://whoisthisjoker.com
      weight: 1
    #- identifier: gallery
     # name: Gallery
      #title: Blog posts
      #url: /gallery
      #weight: 2
    #Dropdown menu
     #- identifier: dropdown
      # title: Example dropdown menu
       #name: Dropdown
       #weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Daniel Jones Portfolio"
  description: Daniel Jones Resume/CV
  # staticPath: ""  # The path to serve the static files from
  favicon: /fav.svg

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: true

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Daniel Jones CV" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Daniel Jones"
    subtitle: "Business Systems Analyst"
    content: "I am a passionate Business Systems Analyst. I started out as a help desk employee in Dallas Texas, however, I quickly escalated my career, and now work full-time as a systems analyst. I pride myself on being a jack of all trades that can handle any problem given to me, no matter how obscure the software, hardware, programming language, or framework may be."
    image: /me.JPG
    bottomImage:
      enable: true
    roundImage: false # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "DanielJonesResume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-git
          url: https://gitea.whoisthisjoker.com
        - icon: fab fa-youtube
          url: https://www.youtube.com/@danjoredd
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/danjoredd/
        - icon: fas fa-book
          url: "https://whoisthisjoker.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/me2.jpg"
    roundImage: false
    content: |-
      I am a systems analyst with four years of IT experience. My specialty is in Linux, networking, SQL, and cloud technology.

      I am currently studying for my Cisco CCNA certification, and my CompTIA Linux+ certification. I hope to achieve both by August.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Linux"
        - "Bash"
        - "Python"
        - "SQL"
        - "Javascript"
        - "Docker"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"

    items:
      - job: "Systems Analyst"
        company: "The Fikes Companies"
        companyUrl: "https://www.fikesinc.com/"
        date: "Nov 2024 - current"
        featuredLink:
          enable: false
          url: "https://www.fikesinc.com/"
        info:
          enable: true
          content: I worked as a Systems Analyst employee at The Fikes Companies.
        content: |
          In 2024 I was offered a remote position for The Fikes Companies which is the parent company for Cefco. I work as a systems analyst, and frequently work in SQL, Powershell, and Windows Server.
          
          Some of my accomplishments while working there include:
          - Writing Powershell scripts to automate server tasks
          - Writing/Editing SQL Stored Procedures
          - Attending meetings with vendors to determine solutions for Business-to-Business software
          - Use PDI to manage user permissions, edit automated tasks, and view reports 

      - job: "Systems Support Analyst"
        company: "LeTourneau University"
        companyUrl: "https://letu.edu"
        date: "Dec 2021 - Nov 2024"
        featuredLink:
          enable: false
          name: "letu.edu"
          url: "https://www.letu.edu/offices/administration-finance/it/staff.html#ContentBlock-1-3"
          info:
            enable: true
            content: LeTourneau was my Alma Mater, and eventual work environment.
        content: |
          After working at IT Yall, I decided to pivot into a more advanced role and ended up working at my Alma Mater who was looking for someone with my level of curiosity.
          
          My job requirements include: 
          - Designing, testing, and implementing solutions for server-side issues
          - Writing complex SQL queries to modify test and production tables
          - Ensuring the smooth running of back-end PHP web scripts, and fix bugs when they appear
          - Managing user permissions via Linux commands such as chmod

      - job: "Help Desk"
        company: "IT Yall"
        companyUrl: "https://ityall.com"
        date: "Feb 2021 - October 2021"
        featuredLink:
          enable: false
          url: "https://ityall.com"
        info:
          enable: true
          content: I worked as a help desk employee at IT Yall.
        content: |
          Upon graduating from LeTourneau University, I had the opportunity to work at IT Yall to get myself started in the industry. While my primary work was help-desk related, I built a C# application to automate our computer tune-up process that saved the company 15 minutes per end user. 
          
          Some of my accomplishments while working there include:
          - Lead developer of their proprietary PC tune-up software
          - Set up wired networks for end-user locations
          - Wrote batch scripts to automate repeatable work such as the new computer onboarding process


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "B.S. of Business Information Systems"
        school:
          name: "LeTourneau University"
          url: "https://letu.edu"
        date: "2017 - 2020"
        GPA: "3.2 out of 4.0"
        content: |-
          classes:
            - Comuter Architecture
              - Learned basics of logic gates, processor design, and MIPS assembly. 
            - Software Engineering 1 & 2
              - Took two classes on Software engineering. The focus of these classes were to learn project management, Agile development practices, and produce our senior design projects.
            - Network Programming
              - Learned how to program with bare sockets, and how to securely transfer data between machines through network programming
      - title: "A.S. Business Management"
        school:
          name: "Paris Junior College"
          url: "https://www.parisjc.edu/"
        date: "2015 - 2017"
        GPA: "3.5 out of 4.0"
        content: |-
          Classes:
            - Accounting
              - Learned the basics of managerial and financial accounting
            - Economics
              - Learned macro and micro economics and how both impact the nation in their own way


          Extracurricular Activities
            - Phi Theta Kappa
              - Volunteer organization that acts as a channel to help college students aid the community
        featuredLink:
          enable: false
          name: "My academic record"
          
     

  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: CompTIA Secure Infrastructure Specialist – CSIS
        content: The CSIS certification is a stackable certification that says that I have met the requirements of, and passed, the CompTIA A+, Network+, and Security+. With this certification I can implement, troubleshoot, and secure office network systems.
        image: CompTIA_CSIS.png
        url: https://www.credly.com/badges/4b8137d9-b549-4c10-bf27-ddc46ead96c0/public_url
      - title: AWS Certified Practitioner
        content: The AWS Certified Cloud Practitioner teaches the basics of cloud technology, and how to optimize the allocation of resources to minimize cost.
        image: aws_practitioner.png
        url: https://www.credly.com/badges/c2a82281-d625-4eb9-93d6-ec12bc1f953d/public_url


  #TODO: enable once projects are done.
  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Bibliofile
        company: Personal Project
        content: Rust program that allows end users to read epub files on the Linux terminal.
        image: /bibliofile2.png
        featured:
          name: Code
          link: https://git.whoisthisjoker.com/Daniel/bibliofile
        badges:
          - "Rust"
          - "Linux"
          - "HTML"
          



  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: If I sound like a great fit for your project/company, email me below and I will quickly respond!
    email: djones@danielreddjones.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false



  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
