baseURL: https://www.danielreddjones.com
languageCode: "en-us"
title: "Daniel Jones portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: https://whoisthisjoker.com
      weight: 1
    #- identifier: gallery
     # name: Gallery
      #title: Blog posts
      #url: /gallery
      #weight: 2
    #Dropdown menu
     #- identifier: dropdown
      # title: Example dropdown menu
       #name: Dropdown
       #weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Daniel Jones Portfolio"
  description: portfolio and CV of Daniel Jones
  # staticPath: ""  # The path to serve the static files from
  favicon: /fav.svg

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Daniel Jones Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Daniel Jones"
    subtitle: "I am a C++ and Rust programmer."
    content: "A passionate embedded systems programmer. I like to make fast, efficient, and clean code that runs on many systems. I currently work as a systems analyst at LeTourneau University, but am seeking to pivot into embedded systems."
    image: /me.JPG
    bottomImage:
      enable: true
    roundImage: false # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "resume.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-git
          url: https://git.whoisthisjoker.com
        - icon: fab fa-youtube
          url: https://www.youtube.com/@danjoredd
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/danjoredd/
        - icon: fas fa-book
          url: "https://whoisthisjoker.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/me2.jpg"
    roundImage: false
    content: |-
      I am a software developer with a passion for embedded development. I have a background in computer information systems, and have primarily worked in the realm of Information Technology. In my spare time I am always programming, and I have decided that I want to pursue this as a full-time job. 

      I am currently working on a project called Bibliofile that will allow people with low-end hardware to read ebooks, helping spread the love of literature to low-income communities.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "C"
        - "C++"
        - "Python"
        - "QT"
        - "CLion"
        - "Rust"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Systems Analyst"
        company: "LeTourneau University"
        companyUrl: "https://letu.edu"
        date: "Dec 2021 - present"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "I currently work as a systems analyst at LeTourneau University. My job requirements include analyzing faulty code, ensuring the smooth running of back-end scripts, and managing user permissions. I am currently part of a project that includes us changing our ERP to a cloud-based solution."

      - job: "Help Desk"
        company: "IT Yall"
        companyUrl: "https://ityall.com"
        date: "Feb 2021 - October 2021"
        featuredLink:
          enable: false
          url: "https://ityall.com"
        info:
          enable: true
          content: I worked as a help desk employee at IT Yall.
        content: |
          I worked as a help desk employee at IT Yall. While my primary work was help-desk related, I built a C# application to automate our computer tune-up process that saved the company 15 minutes per customer.
          - Lead developer of their proprietary PC tune-up software.
          - set up wired networks for end-user locations.
          - wrote batch scripts to automate repeatable work such as the new computer onboarding process.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "B.S. of Business Information Systems"
        school:
          name: "LeTourneau University"
          url: "https://letu.edu"
        date: "2017 - 2020"
        GPA: "3.2 out of 4.0"
        content: |-
          classes:
            - Comuter Architecture
              - Learned basics of logic gates, processor design, and MIPS assembly. 
            - Software Engineering 1 & 2
              - Took two classes on Software engineering. The focus of these classes were to learn project management, Agile development practices, and produce our senior design projects.
            - Network Programming
              - Learned how to program with bare sockets, and how to securely transfer data between machines through network programming
      - title: "A.S. Business Management"
        school:
          name: "Paris Junior College"
          url: "https://www.parisjc.edu/"
        date: "2015 - 2017"
        GPA: "3.5 out of 4.0"
        content: |-
          Classes:
            - Accounting
              - Learned the basics of managerial and financial accounting
            - Economics
              - Learned macro and micro economics and how both impact the nation in their own way


          Extracurricular Activities
            - Phi Theta Kappa
              - Volunteer organization that acts as a channel to help college students aid the community
        featuredLink:
          enable: false
          name: "My academic record"
          
     

  # Achievements
  achievements:
    enable: false
    title: "Volunteer Work"
    items:
      - title: Network Admin and Media Manager (2021 - current)
        content: Worked as media manager and Network Admiinistrator for Longview First Church. 
        url: https://www.longviewfirst.com/
        image: https://s3-media0.fl.yelpcdn.com/bphoto/H5JSX44NgJwxqTy_2T24kQ/o.jpg
      - title: Phi Theta Kappa (2016-2017)
        content: Phi Theta Kappa is a volunteer fraternity that seeks to provide help to those in need. While a member, I assisted in mailing Christmas cards to the people in hospitals.
        image: https://www.ptk.org/wp-content/themes/ptk/images/logo.svg
      - title: Civil Air Patrol(2011 - 2013)
        content: Civil Air Patrol is the Air Force auxillary for civilian teenagers to volunteer their time. While enrolled I assisted primarily in visiting veterans at the VA.
        url: "https://www.gocivilairpatrol.com/"
        image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Seal_of_the_United_States_Civil_Air_Patrol.svg/1024px-Seal_of_the_United_States_Civil_Air_Patrol.svg.png


  #TODO: enable once projects are done.
  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Bibliofile
        content: An E-Reader with both TUI and GUI versions available. The purpose of this project is to help spread the love of books by providing low-resource intensive software
        image: /images/projects/profile.png
        featured:
          name: Download
          link: https://hugo-profile.netlify.app
        badges:
          - "Rust"
          - "QT"
          - "TUIkit"
        links:
          - icon: fab fa-git
            url: https://git.whoisthisjoker.com/Daniel/bibliofile
          
      - title: Daily Bread
        content: C++ QT6 widget that displays Bible verses daily to the end-user.
        image: /images/projects/converter.jpg
        featured:
          name: Download
          link: https://git.whoisthisjoker.com/Daniel/DailyBread
        badges:
          - "C++ 17"
          - "QT 6"
        links:
          - icon: fab fa-git
            url: https://github.com/gurusabarish/converter

      - title: Empire Dice
        content: Android app for the Table Top Roleplaying system "Edge of the Empire.""
        image: /images/projects/profile2.jpg
        featured:
          name: Download
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Android"
          - "Kotlin"
          - "Android Studio"
        links:
          - icon: fab fa-git
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: If I sound like a great fit for your project/company, email me below and I will quickly respond!
    email: danielreddjones@protonmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
 

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
